### ISSUE TITLE
regex problem

### ISSUE THREAD

**Issue by Matrixbirds** [Lellansin/Cipher-examples#1]
``` regex
/[\W]*[\w][\W]*/g
```

这个意思是匹配所有字符？

**Comment by Lellansin** [comment]
@Matrixbirds  准确说是  <pre>/[\W]_（[\w]）[\W]_/g  </pre> 这里是匹配中间的一个字母，以及这个字符周围所以的其他非字母的字符比如空格、逗号之类的，匹配完了之后大概会匹配到这样的：  35A,2  的结果，然后由于中间的括号我记忆了中间的那一个字母，所以我可以单独拿到 A，转换之后返回填充到 replace 的结果，其他的非字母则在 repalce 匹配的时候去掉了。

**Comment by Matrixbirds** [comment]
get 在ruby中遇到了一些问题。。
